version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: newsfeed-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: newsfeed
      MYSQL_USER: newsfeed
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - newsfeed-network

  redis:
    image: redis:7-alpine
    container_name: newsfeed-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - newsfeed-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: newsfeed-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - newsfeed-network

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  newsfeed-network:
    driver: bridge 
 